### ISSUE TITLE
Have a way to look at your goals

### ISSUE THREAD

**Issue by kellyjadams** [Break-Into-Data/Break-Into-Data-Discord-Bot#31]
Ability to check how many goals you've set (including the metrics you set it at). Good for if you set more than one and/or forgot your goals.

**Comment by kellyjadams** [comment]
Example: 

Fitness: Weightlifting for 45 minutes 4 times a week.
Studying: Japanese for 15 minutes 5 times a week.

**Comment by meri-nova** [comment]
> Example:
> 
> Fitness: Weightlifting for 45 minutes 4 times a week. Studying: Japanese for 15 minutes 5 times a week.

This is delicious stuff. Thank you. We actually implemented and you can reap the benefits of your contribution, our Queen Analyst.
